### ISSUE TITLE
Java examples should be in try catch block?

### ISSUE THREAD

**Issue by deekoder** [minio/docs.minio.io#102]
Need to clarify with the team.

**Comment by deekoder** [comment]
Bala how about the : putObject(String bucketName, String objectName, String fileName) example

**Comment by deekoder** [comment]
Please also update Javadocs.

**Comment by harshavardhana** [comment]
It should be we don't need to throw exceptions which we can catch and reply properly.

**Comment by deekoder** [comment]
Done on docs. Javadocs and examples for all SDKs in github use s3Client variable.

**Comment by deekoder** [comment]
PR is sent.
