### ISSUE TITLE
Take a first iteration to explain Minio Server Policy Document

### ISSUE THREAD

**Issue by deekoder** [minio/docs.minio.io#103]
Feel free to not be constrained by the format we have now. Basically please explain what we have implemented, and what is not implemented for Server Policy.

**Comment by hackintoshrao** [comment]
Sure. Will send a write up today.

**Comment by hackintoshrao** [comment]
@deekoder : Getting more ideas for content from @harshavardhana , not sure what exactly should go in there.

**Comment by hackintoshrao** [comment]
@deekoder : I have updated the docs, please review https://docs.minio.io/v1.0/docs/minio-server-bucket-policy .

**Comment by deekoder** [comment]
KP - we need more info than what you have. Let's chat on gitter.

**Comment by deekoder** [comment]
We will address this via mc and APIs in the next release of docs.
