### ISSUE TITLE
Typos in Minio server bucket policy docs

### ISSUE THREAD

**Issue by awwalker** [minio/docs.minio.io#108]
-- Underneath "Nested policy support." -- instead of reading nested policies are not allowed, it should say "Nested policies are not supported". To be consistent with the blobs on user policy support and IAM policy support.

-- Underneath "IAM policy support." -- There is a missing period after "IAM policy not supported"

-- Underneath the two tables describing access policies and their permissions -- "The term publicly tells" should read "The term publicly means"

-- Underneath "Access policies explained" inside the _none_ blob -- "That is without using secret or access keys its not be possible..." should read "That is without using secret or access keys it is (or it's) impossible..."

-- Underneath "Access policies explained" inside the _readonly_ blob -- There is either a missing period after "copy your file into the bucket" or an extra period after check the default access policy. The instructions are inconsistent with their formatting.

-- Underneath "Access policies explained" inside the _readonly_ blob -- There is a missing apostrophe in the "Lets do a simple operation..." should be "Let_'s_".

-- Underneath "Access policies explained" inside the _readonly_ blob -- In the check the default access policy instructions it should say: "play is a self hosted Minio server on the cloud, running at play.minio.io. (add period not comma) _It's_ freely accessible and its keys are configured by default. (add period) On mc play is an alias set by default for ... "

-- Underneath "Access policies explained" inside the _readonly_ blob -- Move the description of the play service to under the first instruction where it is used so that users know from that start what play is and that it exists.

-- Underneath "Access policies explained" inside the _readonly_ blob -- There is inconsistent capitalization in the instructions as well. Both "copy" and "check" are uncapitalized whereas "Try accessing" and "Set the access" are capitalized. 

 -- Underneath "Access policies explained" inside the _readonly_ blob -- In the "Try accessing" instructions there is a run-on sentence. The sentence can be broken into three separate sentences. The first ending at "using keys". The second ending at "signed by default". And the third ending at "file publicly". 

-- Underneath "Access policies explained" inside the _readonly_ blob -- In the "Try accessing" instructions it should be "let's (missing apostrophe) use the browser to send _an_ HTTP request _to attempt_ (no make an needed) to access the file publicly"

-- Underneath "Access policies explained" inside the _readonly_ blob -- In the "Try accessing" instructions it should say "Since the default permission is none, this attempt at public access is forbidden and the file is inaccessible", just so this line is consistent with the next line which says "the file will be accessible"

-- Underneath "Access policies explained" inside the _readonly_ blob -- In the "Set access" instructions it should say "Now when attempting to access..."

-- Underneath  "Access policies explained" inside the _readwrite_ blog -- It should say "Setting this access policy allows for both public read and public write operation_s_..."

-- "Setting permissions for subset of objects in a given bucket" should read as "Setting permissions for _a_ subset of objects in a given bucket"

-- Underneath "Setting permissions for subset of objects in a given bucket" -- should read as "Exclusive permissions can be set for _a_ subset of..."

-- Underneath "Setting permissions for subset of objects in a given bucket" -- Instead of "Here is how to do it" something along the lines of "Let's see how" will be more consistent with the previous example for _readonly_.

-- Underneath "Access policy JSON configuration." -- You can get rid of the first sentence and make the new first sentence read "JSON-based access policy language is what buckets stored in Minio server use for the access policy configurations." Having the first sentence read "The following section..." is repetitive and unneeded.

**Comment by deekoder** [comment]
Not applicable for v1.0.  Needs to be reopened later if necessary.
