### ISSUE TITLE
Edits in Go Music Player App

### ISSUE THREAD

**Issue by awwalker** [minio/docs.minio.io#110]
1. In the first paragraph -- The third sentence should be "The media inside a bucket is listed in the playlist, and secure URLs are generated on demand..."

2. In step 1 of Set Up Bucket -- The first sentence should be "We've created a public minio server at ... for developers to use as a sandbox" (no need for "object storage")

3. Inconsistent capitalizations -- Some steps have every word capitalized like "Set Up Bucket" whereas others only have the first word capitalized.

4. Inconsistent periods -- Some steps like "Environment variables." include periods while others like "Set Up Bucket" do not.

5. Under "Building playlist." -- The paragraph should be "The first thing the player does is build a playlist by using the ListObjects method to list all the media assets in your media bucket (specified when starting the player). These objects will be rendered as a playlist for the media player like in the player image above. Each object is collected and sent to the browser in JSON format.

The following flow diagram and sample code provide an overview on how this is achieved."

6. Under "Streaming the media." -- The paragraph should be "When a user clicks to play some media on the browser secure URLs are generated on demand by the media player. In order to do this the player uses PresignedGetObject. The secure URL generated by PresignedGetObject is then used by the player to stream the media from the S3 server directly.
The following flow diagram and sample code provide an overview on how this is achieved.
(I think the following sentence should come last because it does not deal with Minio explicitly)
For more information about PresignedGetObject please read this AWS article on Sharing an Object with Others."

**Comment by deekoder** [comment]
1/2/3/4/5 & 6 done.
