### ISSUE TITLE
Edits in Android Photo App

### ISSUE THREAD

**Issue by awwalker** [minio/docs.minio.io#112]
1. There are inconsistent periods after the different steps -- Step 2 Has one after "build this app", Step 4 has one after "Finish" Step 5 has one after "AndroidPhotoApp". 

2. There are also inconsistent periods after the bullet points in Step 3 specifically bullets 1 and 2.

3. In the bullet points of step 3 "Let's" should be cut out of bullet points 1 and 3.

4. The numbering is off by 1. There are two black 3's (App Layout and MainActivity.java).

5. Inside MainActivity.java text Instead of "We write a small helper function to convert the InputStream to String" should be "We use a small helper function to convert the InputStream to String" (its also missing a period)

6. There is also a missing period in the last line of text in the text blurb for MainActivity.java

7. There are inconsistent periods in the bullet points in step 6. Specifically only the last bullet point is lacking a period.

8. There is a missing period in the line below the first picture in Step 3 App Layout "Below is also the full XML version of our design..."

**Comment by deekoder** [comment]
Fixed numbering #3.

**Comment by deekoder** [comment]
1. Done
2. Done
3. Ok sure. Done.
4. Done
5. Done
6. Done

**Comment by deekoder** [comment]
7.Done
8.Done
