### ISSUE TITLE
Edits in RoR Resume Uploader

### ISSUE THREAD

**Issue by awwalker** [minio/docs.minio.io#114]
1. The first text blob is inconsistent in how it refers to Minio Server. First it says "that works with _the_ Minio Server" but in the next sentence it says "to _a_ Minio Server". These need to both be either _the_ or _a_.

2. Replace "cd jobshop" from the Install instructions with cd ror-resumeuploader-app.

3. In Set Up Bucket step it should say "Use _the_ mc mb command to accomplish this"

4. Inconsistent periods in the bullet points after Step 5 Upload Objects -- The first two points have periods but the last two do not.

**Comment by deekoder** [comment]
1. Settled for 'a' Minio Server.
2. Done
3. Done
4. Done
