### ISSUE TITLE
Recipes: Generate Let's Encrypt - Intro typos

### ISSUE THREAD

**Issue by awwalker** [minio/docs.minio.io#138]
First sentence should be "Let's Encrypt is a new Certificate Authority." (period not colon) Or rewritten into one sentence. such as
"Let's Encrypt is a new free, automated, and open source, Certificate Authority."

Also we should not use ampersands in our text it looks hasty. "It is open source and another project from Minio."

**Comment by deekoder** [comment]
There is no ampersand. I think you mean :

**Comment by awwalker** [comment]
I see an ampersand... "It is open source & one of related project from Minio."
