### ISSUE TITLE
Recipes: Generate Let's Encrypt - PreReqs bullets

### ISSUE THREAD

**Issue by awwalker** [minio/docs.minio.io#139]
second bullet should be 
- Install Minio Server from here. to be consistent with other recipes.

Other prereqs besides the install minio server might be better placed under a different header such as Dependencies since they do not directly relate to Minio.

The capitalization of concert is inconsistent. In the Root access is needed bullet. It is capitalized in the next sentence. It shouldn't be just like in the Port 443 bullet.

**Comment by deekoder** [comment]
I refactored it
