### ISSUE TITLE
Minio Client Utility: Minio Client Complete Guide - Command diff typos

### ISSUE THREAD

**Issue by awwalker** [minio/docs.minio.io#156]
The blob here should be:

"diff command computes the differences between two directories. It only lists content that is missing or that differs in size. It DOES NOT compare the content, so it is possible that objects with the same name and of the same size, but with differences in content are not detected. This way, it can perform high speed comparisons on large volumes of data or between sites."

**Comment by GarimaKapoor** [comment]
Done
