### ISSUE TITLE
Minio Client Utility: Minio Client Complete Guide - Example format inconsistency

### ISSUE THREAD

**Issue by awwalker** [minio/docs.minio.io#157]
In Step 3 the format of the examples is:

Example - Minio Cloud Storage
Example - Amazon S3 Cloud Storage
Example - Google Cloud Storage

In Step 6 the format of the examples is:

_Example: [text]_

In Step 7 the format of the examples is:

Example:
[text]

I think one format needs to be picked and continuously used otherwise it is distracting and harder to isolate examples since they keep changing how they look.

**Comment by GarimaKapoor** [comment]
Done, following the format of Example: [text]
