### ISSUE TITLE
Minio Client Utility: Minio Client Complete Guide - Command access / Command session example inconsistency

### ISSUE THREAD

**Issue by awwalker** [minio/docs.minio.io#158]
See #157 before fixing this. 

In Command access the examples are formatted as:

Example #: [text]

(Also Example 1 here is missing a space between Example and 1)

But in Command session the examples are formatted as:

Example: # 
[text]

**Comment by GarimaKapoor** [comment]
Removed the number in front of the examples, solves no purpose when we are describing what examples are.
