### ISSUE TITLE
Minio Client SDK: Java Client API Reference - Bucket operations extra lines

### ISSUE THREAD

**Issue by awwalker** [minio/docs.minio.io#165]
There are lines after each Bucket operation headers in the java client API Reference docs that are pretty repetitive in the info they provide. If we keep the tables describing return types in this doc I dont think these lines are necessary.

"public List<Bucket> listBuckets()" for example can be inferred from the table as well as the header.

**Comment by GarimaKapoor** [comment]
All other SDKs has description before the bucket operation. AWS follows the same style. We can maintain what we have.
