### ISSUE TITLE
Minio Client SDK: JavaScript Client API Reference - Inconsistent prefix param description

### ISSUE THREAD

**Issue by awwalker** [minio/docs.minio.io#166]
In these docs prefix has been given the description "The prefix of the objects that should be listed (optional, default '')". None of the other docs that use this same format include the optional part of the description. In fact in JavaScript docs in the description of prefix in the listIncompleteUploads section the (optional, default '') is not there either. So either we should add it everywhere or remove it from this one place.

**Comment by deekoder** [comment]
I think this could be a language specific issue on how it deals with optional, defaults. I am not sure so need to ask krishna.

**Comment by GarimaKapoor** [comment]
I asked Krishna earlier, He mentioned that istIncompleteUploads needs to be updated with (optional, default '')

**Comment by GarimaKapoor** [comment]
Krishna has updated the js. We can close this issue.
