### ISSUE TITLE
Minio Client SDK: Golang Client API Reference/JavaScript Client API R/Python Client API R - Inconsistent filePath descriptions

### ISSUE THREAD

**Issue by awwalker** [minio/docs.minio.io#170]
These are in the FGetObject tables...

In the Golang API Reference filepath is described as:
"path to which the object data will be written to."

In the JavaScript Docs filepath is:
"Path on the local file system to which the object data will be written to."

In the Python Docs filepath is:
"Local path where object data will be written to"

We need to pick one and be consistent

**Comment by awwalker** [comment]
@deekoder @GarimaKapoor can you pick one and I will change the others appropriately?

**Comment by GarimaKapoor** [comment]
JS is the most accurate and clear description. Lets stick to that.

**Comment by awwalker** [comment]
Went with "Path on the local filesystem to which the object data will be written."
