### ISSUE TITLE
Minio Client SDK: Golang API R / JavaScript API R / Python API R - missing failure sentence

### ISSUE THREAD

**Issue by awwalker** [minio/docs.minio.io#171]
In the Java Client API Reference for putObject and fputObject in the text before the example it ends with "If a different object is being uploaded, then the upload will fail." All the other docs are missing this sentence.

**Comment by GarimaKapoor** [comment]
yes we need to update everywhere else

**Comment by GarimaKapoor** [comment]
changed the putObject and fputObject description across all the SDK's. Closing the issue
