### ISSUE TITLE
Minio Client SDK: Golang QS Guide - Intro Language capitalization

### ISSUE THREAD

**Issue by awwalker** [minio/docs.minio.io#179]
In the Go intro it reads "an example go program...This document assumes that you have a working Golang setup in place." 

We should capitalize the "go".

**Comment by deekoder** [comment]
I think this is ok.

**Comment by awwalker** [comment]
Most places capitalize it. It is like the Python issue...it's a language not a verb here

**Comment by awwalker** [comment]
Done. The Golang docs https://golang.org/doc/ capitalize it so I did.
