### ISSUE TITLE
Minio Client SDK: Python QS Guide - Intro Language capitalization

### ISSUE THREAD

**Issue by awwalker** [minio/docs.minio.io#180]
The python intro paragraph reads "execute an example python program....assumes that you have a working python setup in place"

Both of these pythons should be capitalized

**Comment by deekoder** [comment]
why so. It's pretty common to say python in the middle of a sentence.

**Comment by awwalker** [comment]
But it is supposed to be Python...it is a language not a snake. Even if its common doesn't make it right. A quick google search of Python programming most places capitalize it

**Comment by GarimaKapoor** [comment]
I agree, We have to make it cap P. I made the edit closing the issue. I checked out the other documentaion MongoDB and AWS. Both consistently use P cap in Python or use Py for short.
