### ISSUE TITLE
Minio Client SDK: Python / JavaScript / Golang QS 'secure vs ssl'

### ISSUE THREAD

**Issue by awwalker** [minio/docs.minio.io#182]
In the Python and JS Docs the param is called secure. The Golang docs use ssl in the table and example. These should be consistent.

**Comment by deekoder** [comment]
I will assign it to harsha to evaluate this suggestion.

**Comment by GarimaKapoor** [comment]
Changed Go param to secure from ssl after consulting with Harsha. Closing it
