### ISSUE TITLE
Collect Recipe Content

### ISSUE THREAD

**Issue by deekoder** [minio/docs.minio.io#22]
Compile and collect a list of "How Tos" for each category (Minio Server / Minio Client / Minio SDKs). 
- Park the question and content in Readme.io
- Maintain an excel of who asked this question (who asked, when, how many people asked the same question, Is the a Server/Client or SDK question)

**Comment by koolhead17** [comment]
Closing this, I have google doc where am maintaining the same list.  
We additionally are also maintaining developer FAQ.

Both are ongoing task.
