### ISSUE TITLE
mc is capitalized in the QS guide

### ISSUE THREAD

**Issue by deekoder** [minio/docs.minio.io#31]
Under 

2. Run mc heading appears like Run MC

**Comment by deekoder** [comment]
For now I will change this to Run Minio Client. But I want to say Run mc

**Comment by koolhead17** [comment]
@deekoder To me it seems to be design/css, capitalize everything followed by ## @rushenn will be able to confirm the same.

**Comment by rushenn** [comment]
Fixed.
