### ISSUE TITLE
Format mc examples Headings

### ISSUE THREAD

**Issue by deekoder** [minio/docs.minio.io#32]
Use 1 / 2 / 3 numbers instead of stars to indicate headings in the "How to use mc" https://docs.minio.io/docs/example-guide

**Comment by koolhead17** [comment]
@deekoder lets talk on this one tomorrow, I remember Rushan playing with the CSS for that star also if now we are going to add numbers there we will have to modify it in similar fashion across documentation. Having a single style guideline across doc will be great.

**Comment by deekoder** [comment]
Reassigning this to Rushan. Rushan we want to say in the heading 2. Run mc  instead of Run Minio Client
