### ISSUE TITLE
Remove Misc heading

### ISSUE THREAD

**Issue by deekoder** [minio/docs.minio.io#34]
No reason for us to teach others how to install go lang in our docs.  If we are mingling the app dev audience and the contributing devs, we have to manage this more consciously.

**Comment by GarimaKapoor** [comment]
Installing golang is not simple. It will be nice to guide people to correct place on how to install. We can remove the heading. Instead we can  put a link to how to install golang in the relevant section (Minio Go Library)

**Comment by deekoder** [comment]
ok that sounds good to me. It needs a proper home.

**Comment by GarimaKapoor** [comment]
I just checked the golang quick start guide. It already has a link to install. In that case we can remove the how to entirely.

**Comment by koolhead17** [comment]
Please provide me little reference, what & where are we planning to remove it from?
How to install Golang will be needed in all places where we are talking about source install reference of Minio Server, mc, concert & minio-go.  We should let the reference on how to install somewhere on all these docs.

**Comment by GarimaKapoor** [comment]
Atul, the plan to give the link of the go install where ever it is required and remove the misc How to. The point is that it should not be outside on its own!

**Comment by GarimaKapoor** [comment]
For server and client you don't have to put the link to install go. Only if the installation is from source you need install go.

**Comment by GarimaKapoor** [comment]
For concert, you can add one line if installing for source. You will also need to install Golang and you give the link to install Golang there.

**Comment by koolhead17** [comment]
Garima added the reference for install for golang for  concert under assumptions section. 

Also we have mentioned about installing golang in install from source tab for minio client, If we like this practice, we can follow the same for minio server quickstart guide too. That ways we will remove the NOTE part from minio server QS.

**Comment by koolhead17** [comment]
Closing this
