### ISSUE TITLE
Minio Client Full Guide

### ISSUE THREAD

**Issue by deekoder** [minio/docs.minio.io#36]
- Explain the configuration of mc for play / aws / google cloud
- When in doubt ok to specify default option even if not needed to educate user.  s3v4 e.g. given by ab
- Explain each command.
- Explain the options for each command.
- Show for Play & AWS
- Show outputs.

**Comment by GarimaKapoor** [comment]
Deepa, Minio Client complete guide can be a bug, it will go under this release

**Comment by koolhead17** [comment]
Closing this, as all contents are added to our guide.
