### ISSUE TITLE
Remove tabs from API References

### ISSUE THREAD

**Issue by deekoder** [minio/docs.minio.io#37]
Readability issue. Dev should grasp a full api (with desc/ args/ return/eg ) as a block

Javascript / Java - Deepa
Go / Py / .NET - Atul
UX - Rushan

**Comment by koolhead17** [comment]
@deekoder Let me take care of this all, it will avoid confusion. Assign this all to me. I will get this done.

**Comment by deekoder** [comment]
Since Atul and Rushan took care of this already. Assigning this to them. And then closing it since its done.
