### ISSUE TITLE
Oauth & Sub Categories Support 

### ISSUE THREAD

**Issue by deekoder** [minio/docs.minio.io#43]
Need to reach out to support.

**Comment by deekoder** [comment]
Done. Awaiting reply.

**Comment by GarimaKapoor** [comment]
I was discussing this  with AB.  Till we get Oauth functionality from readme. We can put our own edit button which can link to the respective library/server/client in Github and users can edit or fork it there.  We can discuss more how/ whether to go this route.

**Comment by deekoder** [comment]
Pending reply. No word.

**Comment by deekoder** [comment]
Closing this.
