### ISSUE TITLE
Replace tiff to png screenshots. 

### ISSUE THREAD

**Issue by koolhead17** [minio/docs.minio.io#62]
The example app https://docs.minio.io/docs/minio-java-rest-example-app is using tiff format in few screenshots, it needs to be changed to png so that it can render on browser.

_This is how it appears currently._

![screenshot 2016-04-11 17 05 36](https://cloud.githubusercontent.com/assets/41746/14425864/197f51d0-0008-11e6-80ca-1d7730fccd4e.png)

**Comment by deekoder** [comment]
Fixed.
