### ISSUE TITLE
minio-server: Step3 explore further can be a dropdown to show more information. 

### ISSUE THREAD

**Issue by harshavardhana** [minio/docs.minio.io#7]

**Comment by rushenn** [comment]
I think we can remove step 3 as we have dropdown on top

**Comment by harshavardhana** [comment]
> I think we can remove step 3 as we have dropdown on top

:+1:  - listing all the issues here, we can look and close.

**Comment by deekoder** [comment]
No we should not hide it behind a click call to action. User is exploring so reveal it. Let's discuss

**Comment by deekoder** [comment]
Leave this as is while we figure out Readme.io

**Comment by deekoder** [comment]
Agreed that it does not need to be a dropdown.
