### ISSUE TITLE
Bring Github Readme pages to coincide with QS Guide pages

### ISSUE THREAD

**Issue by deekoder** [minio/docs.minio.io#75]
Make changes to markdown as needed.

**Comment by koolhead17** [comment]
As discussed, this required re-writing the whole content in native markdown.  Once we have our doc site launched, i will take care of this.

**Comment by deekoder** [comment]
This is now no longer a low priority as per discussion today.

**Comment by deekoder** [comment]
Atul - Java is done.
Please do the Readme for JS / Py & Go
