### ISSUE TITLE
Minio Java Client SDK Reference : Exceptions should be documented

### ISSUE THREAD

**Issue by deekoder** [minio/docs.minio.io#76]

**Comment by deekoder** [comment]
Needs further discussion

**Comment by deekoder** [comment]
Need info from SDK owner to complete this.

**Comment by balamurugana** [comment]
Do we want to document all of these http://minio.github.io/minio-java/io/minio/errors/package-summary.html ? As we have reference to this javadoc, is it good idea to have link to the page than documenting them once again?

**Comment by GarimaKapoor** [comment]
@balamurugana  MinioException is not documented. Take a look at this source.
https://github.com/minio/miniojava/blob/9c5b4d61c18fef6592d5ce364909dd263767f4ac/src/main/java/io/minio/errors/MinioException.java
