### ISSUE TITLE
Please review text for putObject description : Java

### ISSUE THREAD

**Issue by deekoder** [minio/docs.minio.io#82]
putObject : If the session fails, the user may attempt to re-upload the object by creating the exact same object again. All parts of any current upload session will be examined and attempt to resume the session automatically. If a mismatch is discovered, upload will fail. Otherwise, it will resume uploading where the session left off.

**Comment by balamurugana** [comment]
The message is clear.  I think below text can be changed to

> All parts of any current upload session will be examined and attempt to

All parts of any current upload session will be examined and attempted to

**Comment by deekoder** [comment]
https://docs.minio.io/docs/java-client-api-reference#putObject
How about something more user friendly such as this : 

In the event that putObject fails to upload an object, the user may attempt to re-upload the object by creating the exact same object again.  If the same object is being uploaded, the upload examines the previous partial attempt to upload this object using putObject and resumes automatically from where it left off. If a new object is being uploaded instead, then the upload will fail.

**Comment by GarimaKapoor** [comment]
Also, we need to make this comment common for all the putObject as incomplete mulitpart upload applies to all the put Object and not just for this particular case.

**Comment by GarimaKapoor** [comment]
What we can do is that under the putObject , right below the line of 'Uploads an object from a stream/Buffer.' We can make a subtitle of Multipart Upload. In this Multipart upload we can provide a brief description of the max size of the object, How the multipart blocks are calculated by default it is 5MB but we can go upto 5GB etc.

**Comment by balamurugana** [comment]
How about having below description.
```
PutObject(): uploads given data as object in the bucket. The function works in two ways.  If data size is <= 5MiB, it's uploaded in a single put call. If data size > 5MiB, it is uploaded as multipart put where data is split by multiple of 5MiB chunks with maximum of 10000 chunks and uploaded each chunk separately, then those chunks are assembled to make the big final object.

When multipart chunk upload fails, the next PutObject() to same object will resume the chunk upload where it left off previously.  If a failure at resume will abort the resume and the data is uploaded freshly from the beginning.
```

**Comment by balamurugana** [comment]
> https://docs.minio.io/docs/java-client-api-reference#putObject
> How about something more user friendly such as this :
> 
> In the event that putObject fails to upload an object, the user may attempt to re-upload the object by creating the exact same object again. If the same object is being uploaded, putObject API examines the previous partial attempt to upload this object and resumes automatically from where it left off. If a different object is being uploaded, then the upload will fail.

LGTM

**Comment by GarimaKapoor** [comment]
The maximum size of a single object is limited to 5TB. PutObject transparently uploads objects larger than 5MB in multiple parts. This allows failed uploads to resume safely by only uploading the missing parts. Uploaded data is carefully verified using MD5SUM signatures.

We can add above description before  "In the event that putObject fails to upload an object, the user may attempt to re-upload the object by creating the exact same object again. If the same object is being uploaded, putObject API examines the previous partial attempt to upload this object and resumes automatically from where it left off. If a different object is being uploaded, then the upload will fail."

**Comment by GarimaKapoor** [comment]
Also AB mentioned that different libraries do it a little differently so we will need to ask the library maintainers to add the putObject description to their respective SDK.

**Comment by deekoder** [comment]
Completed.

**Comment by GarimaKapoor** [comment]
Just saw that the description which we discussed is not updated on the languages,. It is carrying older description.

**Comment by GarimaKapoor** [comment]
updated all the SDK's with the new description closing it
