### ISSUE TITLE
 Sign Off from SDK owners for release.

### ISSUE THREAD

**Issue by deekoder** [minio/docs.minio.io#86]

**Comment by harshavardhana** [comment]
@minio/maintainers-minio-java-minio-dotnet-minio-py  @minio/maintainers-minio-js-minio-go-mc-and-file-browser 

Sign-Off needed.

**Comment by krishnasrinivas** [comment]
Fixed the minio-js docs.

**Comment by deekoder** [comment]
JS - Signed Off
Java - Signed off (pending putObject)
Go - Signed off
Python - Pending owner's ACK.

**Comment by harshavardhana** [comment]
Python Signed Off as well.

**Comment by GarimaKapoor** [comment]
Krishna signed off on the JS made some changes and fixed couple of things.

**Comment by deekoder** [comment]
Harsha also signed off on Py & Go
