### ISSUE TITLE
minio-server: Server page needs to have 'mc' cli examples first, followed by 'aws cli'

### ISSUE THREAD

**Issue by harshavardhana** [minio/docs.minio.io#9]
- 's3cmd' can be deferred as further reading.

**Comment by deekoder** [comment]
Oh ok so we want to highlight that minio server can be used without them learning mc.

**Comment by harshavardhana** [comment]
> ok so insert key mc cli examples ahead makes sense in the server pages.

Yeah :+1:

**Comment by deekoder** [comment]
Part of clean up QS guide.

**Comment by koolhead17** [comment]
Updates, kindly close this after review.
