### ISSUE TITLE
Investigate scrolling issue

### ISSUE THREAD

**Issue by deekoder** [minio/docs.minio.io#92]
The left bar does not scroll often. Only work around is a browser refresh. It's happening way too many times for it to be non systemic.

**Comment by rushenn** [comment]
Fixed it. Tested in Safari, Chrome and Firefox in OSX.

**Comment by deekoder** [comment]
post your update on this issue.

**Comment by deekoder** [comment]
This issue is specific to safari on mac on track pad.

**Comment by deekoder** [comment]
Emailed Readme.io about this bug.

**Comment by rushenn** [comment]
Fixed, please check in your side.
